import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import { FirstComponent } from '../components/FirstComponent'
import { useContextState } from '../context/AppContext'
import MobileNavbar from '../components/MobileNavbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { showMenu } = useContextState()

  return (
    <>
      <Head>
        <title>Volorole</title>
        <meta name="description" content="Generated by Volorole website" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='page_body'>
        <Navbar />
        {showMenu && 
          <div className='fixed w-full lg:hidden'><MobileNavbar /></div>
        }
        <FirstComponent />
      </div>
    </>
  )
}
